repoURL: https://github.com/kimsehwan96/numble-k8s

apps:
  - name: apps
    namespace: argocd
  - name: argocd
    namespace: argocd
  - name: nginx
    namespace: nginx
  - name: istio
    namespace: istio-system
    ignoreDifferences:                                                                                                                   
      - group: admissionregistration.k8s.io                                                                                                
        jqPathExpressions:                                                                                                                 
        - .webhooks[].failurePolicy                                                                                                        
        kind: ValidatingWebhookConfiguration                                                                                               
        name: istio-validator-istio-system   
  - name: eck-operator
    namespace: elastic-system
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[]?.clientConfig.caBundle
  - name: eck-elasticsearch
    namespace: elastic-system
  - name: eck-kibana
    namespace: elastic-system