repoURL: https://github.com/kimsehwan96/numble-k8s

apps:
  - name: apps
    namespace: argocd
  - name: argocd
    namespace: argocd
  - name: nginx
    namespace: nginx
  - name: istio
    namespace: istio-system
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        jsonPointers:
          - /webhooks/0/failurePolicy
  - name: eck-operator
    namespace: elastic-system