repoURL: https://github.com/kimsehwan96/numble-k8s

apps:
  - name: argocd
    namespace: argocd
  - name: nginx
    namespace: nginx
  - name: istio
    namespace: istio-system
    ignoreDifferences:
      - group: admissionregistration.k8s.io/v1
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
          - .webhooks[0].failurePolicy