apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
  namespace: {{ template "nginx.namespace" . }}
  labels:
    app: nginx
    app.kubernetes.io/name: '{{ template "nginx.name" .}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
        imagePullPolicy: "{{ .Values.nginx.imagePullPolicy }}"
        ports:
        - containerPort: 80
    