apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: nginx
spec:
  gateways:
    - nginx-gateway
  hosts:
    - "istio-syste-istio-ingres-da4cf-16957343-bb773de71644.kr.lb.naverncp.com"
  http:
    - match:
        - port: 30002
      route:
        - destination:
            host: nginx-service
            port:
              number: 80
