namespace: argocd

resources:
  - ./argocd-namespace.yaml
  #- ./argocd-gateway.yaml
  #- ./argocd-virtualservice.yaml
helmCharts:
  - name: argo-cd
    includeCRDs: true
    repo: https://argoproj.github.io/argo-helm
    releaseName: argo-cd
    version: 5.28.0
    namespace: argocd
    valuesInline:
      fullnameOverride: argocd
      repoServer:
        containerSecurityContext:
          seccompProfile:
            type: Unconfined
      configs:
        cm:
          application.instanceLabelKey: app.kubernetes.io/instance
          kustomize.buildOptions: --enable-alpha-plugins --enable-helm --load-restrictor LoadRestrictionsNone
          resource.exclusions: |
            - apiGroups:
              - cilium.io
              kinds:
              - CiliumIdentity
              clusters:
              - "*"
        params:
          server.insecure: true