namespace: argocd

resources:
  - ./argocd-namespace.yaml
  #- ./argocd-gateway.yaml
  #- ./argocd-virtualservice.yaml
helmCharts:
  - name: argo-cd
    includeCRDs: true
    repo: https://argoproj.github.io/argo-helm
    releaseName: argo-cd
    version: 5.28.0
    namespace: argocd
    valuesInline:
      configs:
        params:
          server.insecure: true