apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
  namespace: istio-system
spec:
  profile: default
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
          serviceAnnotations:
            service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nlb"
            service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"
          service:
            ports:
              - port: 80
                targetPort: 8080
                name: http2
              - port: 443
                targetPort: 8443
                name: https
              # 현재 도메인을 사용하지 않는 상태에서, 앱을 ingress를 통해 노출하기 위해 
              - name: argocd
                port: 30001
                targetPort: 30001
              - name: nginx
                port: 30002
                targetPort: 30002
              - name: kibana
                port: 30003
                targetPort: 30003
              - name: grafana
                port: 30004
                targetPort: 30004