namespace: elastic-system

helmCharts:
  - name: eck-elasticsearch
    version: 0.2.0
    namespace: elastic-system
    releaseName: elasticsearch
    valuesInline:
      nodeSets:
      - name: default
        count: 1
        config:
          node.store.allow_mmap: false
          xpack.monitoring.collection.enabled: true